### PR TITLE
Multiple code Snippets

### PR DESCRIPTION
**Pull request by jimit105**
Added following code snippets:
* Convert List of Lists to List
* Hide Print Statements
* Split PDF Document page-wise
* Merge PDF Documents

Also, added .gitignore (Python) and link for CONTRIBUTING.md in README file

### CODE REVIEW

**Comment by jimit105** [comment]
@Ram1004 @kunalj101

**Comment by Ram1004** [comment]
Hi @jimit105  

Thanks for your contribution!

Can you please add a little more description of your hacks in the Readme file so that it includes points like - why is it useful, instances where these hacks can be used? 

Regards
Ram

**Comment by jimit105** [comment]
Hi @Ram1004 ,

I have added more description for the code snippets.

**Review by Ram1004 — APPROVED** [review]

**Review by Ram1004 — APPROVED** [review]

**Comment by jimit105** [comment]
@Ram1004 
This pull request is not merged

**Comment by jimit105** [comment]
@Ram1004

**Comment by jimit105** [comment]
Hi @Ram1004 ,
Just to remind...This PR is not merged.

**Comment by Ram1004** [comment]
Hi @jimit105 
Thank you for your contribution :)

**Pull request merged**
